### ISSUE TITLE
Remake social buttons

### ISSUE THREAD

**Issue by rudnitskih** [anastasiia-emets/fitness_landing#11]
The same issue like - https://github.com/oksanarutska/mate-academy-lessons/issues/31

**Comment by rudnitskih** [comment]
Still not fixed.

Just change opacity on hover:
![image](https://user-images.githubusercontent.com/8848858/47952597-bc1fb980-df7a-11e8-90c7-69b82d3f74f5.png)

**Comment by rudnitskih** [comment]
Buttons still not interactive elements - check how Oksana did it: oksanarutska/mate-academy-lessons#31

**Comment by anastasiia-emets** [comment]
![image](https://user-images.githubusercontent.com/40547968/48120157-ff7b7000-e279-11e8-8090-5ffa8a0fbfe1.png)
так можна?
