### ISSUE TITLE
Check features block again

### ISSUE THREAD

**Issue by rudnitskih** [anastasiia-emets/fitness_landing#16]
![image](https://user-images.githubusercontent.com/8848858/47952335-444f9000-df76-11e8-9fa3-5ddd2eed438f.png)

1) Items should be stretch to the block in the bottom.
2) Links styles
3) Links position
4) Remove all `br` from descriptions.

![image](https://user-images.githubusercontent.com/8848858/47952347-91cbfd00-df76-11e8-9c84-ac942b0db636.png)

**Comment by rudnitskih** [comment]
Wrong font-family: 
![image](https://user-images.githubusercontent.com/8848858/48120650-651c2c00-e27b-11e8-9d55-6b224a7ae3ca.png)

**Comment by anastasiia-emets** [comment]
![image](https://user-images.githubusercontent.com/40547968/48121435-9f86c880-e27d-11e8-8f70-663c2e7149f1.png)

**Comment by rudnitskih** [comment]
Wrong font:
<img width="1440" alt="screen shot 2018-11-09 at 11 07 24" src="https://user-images.githubusercontent.com/8848858/48253320-ad6c5300-e40f-11e8-9b5f-8dde4d5be6b6.png">
