### ISSUE TITLE
Border-top on the img

### ISSUE THREAD

**Issue by Stan0men** [anastasiia-emets/fitness_landing#24]
![06-11-2018 161543](https://user-images.githubusercontent.com/23480671/48069897-4b2d0b80-e1df-11e8-8649-d6526bdeb7f6.png)

There is no such top border on the layout.

**Comment by anastasiia-emets** [comment]
![image](https://user-images.githubusercontent.com/40547968/48120454-d8716e00-e27a-11e8-9781-d1b4a90d1539.png)
