### ISSUE TITLE
Icon not on the right place+ too big 

### ISSUE THREAD

**Issue by Stan0men** [anastasiia-emets/fitness_landing#30]
On your project
![08-11-2018 163225](https://user-images.githubusercontent.com/23480671/48204977-e5be5380-e373-11e8-9b6c-df9212760b2f.png)
On layout

![08-11-2018 163127](https://user-images.githubusercontent.com/23480671/48205041-1a320f80-e374-11e8-9af2-21b305f30bd3.png)

**Comment by anastasiia-emets** [comment]
![image](https://user-images.githubusercontent.com/40547968/48206620-84987f00-e377-11e8-81e3-dc754cd29cd1.png)
