### ISSUE TITLE
One of the block(s) is more than 100% of the page 

### ISSUE THREAD

**Issue by Stan0men** [anastasiia-emets/fitness_landing#31]
![08-11-2018 163720](https://user-images.githubusercontent.com/23480671/48205260-97f61b00-e374-11e8-89ec-daf9c0226005.png)

**Comment by anastasiia-emets** [comment]
![image](https://user-images.githubusercontent.com/40547968/48212969-6c2f6100-e385-11e8-9ae2-9e44e876b37f.png)
