### ISSUE TITLE
Mobile: Blocks are not centered

### ISSUE THREAD

**Issue by rudnitskih** [anastasiia-emets/fitness_landing#33]
![image](https://user-images.githubusercontent.com/8848858/48317561-f7fef280-e5fc-11e8-89c6-7f3920b2a18b.png)

**Comment by anastasiia-emets** [comment]
![image](https://user-images.githubusercontent.com/40547968/48421380-0d8f2c00-e765-11e8-9930-e046f56cf75d.png)
