### ISSUE TITLE
Inner horizontal padding should be the same on left and right

### ISSUE THREAD

**Issue by rudnitskih** [anastasiia-emets/fitness_landing#34]
![image](https://user-images.githubusercontent.com/8848858/48317614-3399bc80-e5fd-11e8-8a28-356d48cd9b58.png)

**Comment by anastasiia-emets** [comment]
![image](https://user-images.githubusercontent.com/40547968/48420319-cbfd8180-e762-11e8-93c8-7e22bfd58d7f.png)
