### ISSUE TITLE
Make 2 columns for features on tablet devices

### ISSUE THREAD

**Issue by rudnitskih** [anastasiia-emets/fitness_landing#37]
![image](https://user-images.githubusercontent.com/8848858/48317683-609a9f00-e5fe-11e8-88e3-0d3084043fd6.png)

**Comment by anastasiia-emets** [comment]
![image](https://user-images.githubusercontent.com/40547968/48439973-455f9900-e790-11e8-8f26-ccdeefb17bd5.png)
